version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/autoscaling-project

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root

