version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/autoscaing-project
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/deploy_image.sh
      timeout: 300
      runas: root

