name: Build, Push, and Deploy via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build and push Docker image to Docker Hub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      # Create env file with SHA tag
      - name: Create deploy env file
        run: |
          echo "DEPLOY_IMAGE_TAG=${{ github.sha }}" > scripts/deploy_env.sh

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Create deployment bundle (zip)
      - name: Create deployment bundle
        run: |
          zip -r deploy.zip appspec.yml scripts/

      # Upload to S3
      - name: Upload bundle to S3
        run: |
          aws s3 cp deploy.zip s3://autoscale-codedeploy-bucket/deploy.zip

      # Trigger CodeDeploy deployment
      - name: Deploy to EC2 via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name autoscale-app \
            --deployment-group-name project-autoscale-dg-new \
            --s3-location bucket=autoscale-codedeploy-bucket,key=deploy.zip,bundleType=zip \
            --region us-east-1

