name: Build, Push, and Deploy via SSM

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building Docker image with tag $IMAGE_TAG"
          docker build --no-cache -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

  update-ec2:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Docker image via SSM
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Sending SSM command to update all instances with tag $IMAGE_TAG"
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=project-autoscale" \
            --comment "Pull Docker image $IMAGE_TAG and restart container" \
            --parameters '{
              "commands":[
                "sudo docker rm -f project-autoscale || true",
                "sudo docker image rm -f '"$IMAGE_NAME:$IMAGE_TAG"' || true",
                "sudo docker pull '"$IMAGE_NAME:$IMAGE_TAG"'",
                "sudo docker run -d --name project-autoscale -p 8080:8080 --restart=always '"$IMAGE_NAME:$IMAGE_TAG"'"
              ]
            }' \
            --timeout-seconds 600 \
            --max-concurrency "100%" \
            --max-errors "0"

