name: Build, Push, and Deploy via SSM

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (no cache)
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale
        run: |
          docker build --no-cache -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  update-ec2:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Checkout (for context)
        uses: actions/checkout@v4

      - name: Debug - Check AWS secrets available
        run: |
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then 
            echo "AWS_ACCESS_KEY_ID: MISSING"; 
          else 
            echo "AWS_ACCESS_KEY_ID: FOUND"; 
          fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then 
            echo "AWS_SECRET_ACCESS_KEY: MISSING"; 
          else 
            echo "AWS_SECRET_ACCESS_KEY: FOUND"; 
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Send SSM command to update running instances (clean redeploy)
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale:latest
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=project-autoscale" \
            --comment "Clean Docker redeploy from GitHub Actions" \
            --parameters '{
              "commands":[
                "echo Stopping old container...",
                "sudo docker stop project-autoscale || true",
                "sudo docker rm -f project-autoscale || true",
                "echo Pruning old images and cache...",
                "sudo docker system prune -af --volumes || true",
                "echo Pulling latest image from DockerHub...",
                "sudo docker pull '"$IMAGE_NAME"'",
                "echo Starting new container...",
                "sudo docker run -d --name project-autoscale -p 8080:8080 --restart=always '"$IMAGE_NAME"'",
                "echo ✅ Deployment complete."
              ]
            }' \
            --timeout-seconds 600 \
            --max-concurrency "100%" \
            --max-errors "0"

