name: Full Build, Push, and Multi-Instance Deploy

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (no cache)
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale
        run: |
          docker builder prune -af || true
          docker build --no-cache -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  deploy-all:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to all EC2s (tag: project-autoscale)
        env:
          IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale:latest
        run: |
          echo "Deploying new image to all instances tagged project-autoscale..."
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Name,Values=project-autoscale" \
            --comment "Redeploying latest Docker image across all instances" \
            --parameters '{
              "commands": [
                "echo Stopping old containers...",
                "sudo docker stop $(sudo docker ps -q) || true",
                "echo Removing old containers...",
                "sudo docker rm -f $(sudo docker ps -aq) || true",
                "echo Removing all old images...",
                "sudo docker image prune -af || true",
                "sudo docker rmi -f $(sudo docker images -aq) || true",
                "echo Pulling new image...",
                "sudo docker pull '"$IMAGE_NAME"'",
                "echo Running new container...",
                "sudo docker run -d --name project-autoscale -p 8080:8080 --restart=always '"$IMAGE_NAME"'",
                "echo Deployment done"
              ]
            }' \
            --timeout-seconds 900 \
            --max-concurrency "100%" \
            --max-errors "0"

