name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t haideralvii/project-autoscale:$IMAGE_TAG -t haideralvii/project-autoscale:latest .
          docker push haideralvii/project-autoscale:$IMAGE_TAG
          docker push haideralvii/project-autoscale:latest
          echo "DEPLOY_IMAGE_TAG=$IMAGE_TAG" > scripts/deploy_env.sh

      - name: Zip deployment bundle
        run: |
          zip -r deploy.zip appspec.yml scripts/

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://project-autoscale-bucket/deploy-${GITHUB_SHA::7}.zip --region ap-south-1

      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name autoscaing-app \
            --deployment-group-name autoscaing-deploy-group \
            --s3-location bucket=project-autoscale-bucket,key=deploy-${GITHUB_SHA::7}.zip,bundleType=zip \
            --region ap-south-1 \
            --description "GitHub Actions Deploy - ${GITHUB_SHA::7}"

