name: Deploy to EC2 (AutoScaling)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # === Deploy to Instance 1 ===
      - name: Deploy to Instance 1
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.INSTANCE1_HOST }}
          username: ubuntu
          key: ${{ secrets.INSTANCE1_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale:latest
            sudo docker stop project-autoscale || true
            sudo docker rm project-autoscale || true
            sudo docker run -d --name project-autoscale -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale:latest

      # === Deploy to Instance 2 ===
      - name: Deploy to Instance 2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.INSTANCE2_HOST }}
          username: ubuntu
          key: ${{ secrets.INSTANCE1_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale:latest
            sudo docker stop project-autoscale || true
            sudo docker rm project-autoscale || true
            sudo docker run -d --name project-autoscale -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/project-autoscale:latest

